/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
});
export const ModifierInstance = IDL.Record({
  'modifierInstanceId' : IDL.Nat,
  'modifierType' : IDL.Text,
  'model_url' : IDL.Text,
  'rarity_tier' : IDL.Nat,
  'multiplier_value' : IDL.Float64,
});
export const LandData = IDL.Record({
  'decorationURL' : IDL.Opt(IDL.Text),
  'baseTokenMultiplier' : IDL.Float64,
  'lastChargeUpdate' : Time,
  'upgradeLevel' : IDL.Nat,
  'principal' : IDL.Principal,
  'landId' : IDL.Nat,
  'lastClaimTime' : Time,
  'biome' : IDL.Text,
  'chargeCap' : IDL.Nat,
  'cycleCharge' : IDL.Int,
  'plotName' : IDL.Text,
  'coordinates' : Coordinates,
  'attachedModifications' : IDL.Vec(ModifierInstance),
});
export const Modifier = IDL.Record({
  'name' : IDL.Text,
  'asset_url' : IDL.Text,
  'mod_id' : IDL.Nat,
  'rarity_tier' : IDL.Nat,
  'multiplier_value' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClaimResult = IDL.Variant({
  'success' : IDL.Record({
    'tokensClaimed' : IDL.Nat,
    'newBalance' : IDL.Nat,
    'nextClaimTime' : Time,
  }),
  'mintFailed' : IDL.Text,
  'cooldown' : IDL.Record({
    'currentBalance' : IDL.Nat,
    'remainingTime' : IDL.Int,
  }),
  'insufficientCharge' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Int,
  }),
});
export const LootCache = IDL.Record({
  'owner' : IDL.Principal,
  'tier' : IDL.Nat,
  'cache_id' : IDL.Nat,
  'discovered_at' : Time,
  'is_opened' : IDL.Bool,
});
export const DiscoverCacheResult = IDL.Variant({
  'success' : LootCache,
  'insufficientTokens' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Nat,
  }),
  'paymentFailed' : IDL.Text,
  'insufficientCharge' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Int,
  }),
});
export const GProposal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'votesYes' : IDL.Nat,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'votesNo' : IDL.Nat,
  'category' : IDL.Text,
  'proposer' : IDL.Principal,
});
export const GStakerLeaderboardEntry = IDL.Record({
  'topBiome' : IDL.Text,
  'weight' : IDL.Nat,
  'principal' : IDL.Principal,
  'unclaimedRewards' : IDL.Nat,
  'stake' : IDL.Nat,
  'maxMods' : IDL.Nat,
});
export const GStakeInfo = IDL.Record({
  'weight' : IDL.Nat,
  'lockEndsAt' : Time,
  'claimableVest' : IDL.Nat,
  'unclaimedRewards' : IDL.Nat,
  'stake' : IDL.Nat,
  'pendingVest' : IDL.Nat,
});
export const GVoteRecord = IDL.Record({
  'weight' : IDL.Nat,
  'choice' : IDL.Bool,
  'proposalId' : IDL.Nat,
});
export const GStakeResult = IDL.Variant({
  'transferFailed' : IDL.Text,
  'success' : IDL.Record({ 'newStake' : IDL.Nat }),
  'insufficientTokens' : IDL.Record({
    'available' : IDL.Nat,
    'required' : IDL.Nat,
  }),
});
export const GVoteResult = IDL.Variant({
  'proposalNotFound' : IDL.Null,
  'alreadyVoted' : IDL.Null,
  'notStaker' : IDL.Null,
  'proposalNotActive' : IDL.Null,
  'success' : IDL.Record({ 'weight' : IDL.Nat }),
});
export const ItemType = IDL.Variant({
  'Land' : IDL.Null,
  'Modifier' : IDL.Null,
});
export const Listing = IDL.Record({
  'itemId' : IDL.Nat,
  'listingId' : IDL.Nat,
  'seller' : IDL.Principal,
  'isActive' : IDL.Bool,
  'itemType' : ItemType,
  'biome' : IDL.Text,
  'price' : IDL.Nat,
});
export const PublicLandInfo = IDL.Record({
  'principal' : IDL.Principal,
  'landId' : IDL.Nat,
  'biome' : IDL.Text,
});
export const CrystalKind = IDL.Variant({
  'Cryonix' : IDL.Null,
  'Burnite' : IDL.Null,
  'Synthex' : IDL.Null,
});
export const CrystalTier = IDL.Variant({ 'T1' : IDL.Null, 'T2' : IDL.Null });
export const CrystalItem = IDL.Record({
  'kind' : CrystalKind,
  'tier' : CrystalTier,
  'quantity' : IDL.Nat,
});
export const KeeperHeartItem = IDL.Record({ 'biome' : IDL.Text });
export const BoosterKind = IDL.Variant({
  'B1000' : IDL.Null,
  'B250' : IDL.Null,
  'B500' : IDL.Null,
});
export const BoosterItem = IDL.Record({
  'kind' : BoosterKind,
  'quantity' : IDL.Nat,
});
export const FullInventory = IDL.Record({
  'crystals' : IDL.Vec(CrystalItem),
  'keeperHearts' : IDL.Vec(KeeperHeartItem),
  'boosters' : IDL.Vec(BoosterItem),
});
export const TopLandEntry = IDL.Record({
  'upgradeLevel' : IDL.Nat,
  'principal' : IDL.Principal,
  'landId' : IDL.Nat,
  'biome' : IDL.Text,
  'tokenBalance' : IDL.Nat,
  'plotName' : IDL.Text,
});
export const CacheDropMod = IDL.Record({
  'modId' : IDL.Nat,
  'subtype' : IDL.Text,
  'rarityTier' : IDL.Nat,
  'instanceId' : IDL.Nat,
});
export const CacheDropItem = IDL.Variant({
  'mod' : CacheDropMod,
  'booster' : BoosterItem,
  'crystal' : CrystalItem,
  'keeperHeart' : KeeperHeartItem,
});
export const CacheOpenResult = IDL.Record({
  'energySpent' : IDL.Nat,
  'items' : IDL.Vec(CacheDropItem),
});
export const UpgradeResult = IDL.Variant({
  'maxLevelReached' : IDL.Null,
  'success' : IDL.Record({ 'newLevel' : IDL.Nat, 'remainingTokens' : IDL.Nat }),
  'insufficientTokens' : IDL.Record({
    'required' : IDL.Nat,
    'current' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  'adminGetLandData' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(LandData))],
      ['query'],
    ),
  'adminSetAllModifiers' : IDL.Func([IDL.Vec(Modifier)], [], []),
  'applyModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buy_item' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'cancelListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'claimRewards' : IDL.Func([IDL.Nat], [ClaimResult], []),
  'discoverLootCache' : IDL.Func([IDL.Nat], [DiscoverCacheResult], []),
  'gAdminCloseProposal' : IDL.Func([IDL.Nat], [], []),
  'gAdminWithdrawTreasury' : IDL.Func([IDL.Nat], [], []),
  'gCalcWeight' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'gClaimVestedRewards' : IDL.Func([], [IDL.Nat], []),
  'gCreateProposal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'gGetActiveProposals' : IDL.Func([], [IDL.Vec(GProposal)], ['query']),
  'gGetAllProposals' : IDL.Func([], [IDL.Vec(GProposal)], ['query']),
  'gGetDeveloperFund' : IDL.Func([], [IDL.Nat], ['query']),
  'gGetInsuranceReserve' : IDL.Func([], [IDL.Nat], ['query']),
  'gGetLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GStakerLeaderboardEntry)],
      ['query'],
    ),
  'gGetMyStakeInfo' : IDL.Func([], [GStakeInfo], ['query']),
  'gGetMyVotes' : IDL.Func([], [IDL.Vec(GVoteRecord)], ['query']),
  'gGetStakedBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'gGetTotalWeightedStake' : IDL.Func([], [IDL.Nat], ['query']),
  'gGetTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'gReceiveIncome' : IDL.Func([IDL.Nat], [], []),
  'gStakeTokens' : IDL.Func([IDL.Nat], [GStakeResult], []),
  'gUnstakeTokens' : IDL.Func([IDL.Nat], [], []),
  'gVote' : IDL.Func([IDL.Nat, IDL.Bool], [GVoteResult], []),
  'getActiveListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllLandsPublic' : IDL.Func([], [IDL.Vec(PublicLandInfo)], ['query']),
  'getAllModifiers' : IDL.Func([], [IDL.Vec(Modifier)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFullInventory' : IDL.Func([], [FullInventory], ['query']),
  'getLandData' : IDL.Func([], [IDL.Vec(LandData)], []),
  'getLandDataById' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], ['query']),
  'getLandDataQuery' : IDL.Func([], [IDL.Opt(IDL.Vec(LandData))], ['query']),
  'getLandOwner' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
  'getLandsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(LandData)], ['query']),
  'getModifierById' : IDL.Func([IDL.Nat], [IDL.Opt(Modifier)], ['query']),
  'getModifiersByTier' : IDL.Func([IDL.Nat], [IDL.Vec(Modifier)], ['query']),
  'getMyLootCaches' : IDL.Func([], [IDL.Vec(LootCache)], ['query']),
  'getMyModifierInventory' : IDL.Func(
      [],
      [IDL.Vec(ModifierInstance)],
      ['query'],
    ),
  'getTopLands' : IDL.Func([IDL.Nat], [IDL.Vec(TopLandEntry)], ['query']),
  'getUserListings' : IDL.Func([IDL.Principal], [IDL.Vec(Listing)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'list_item' : IDL.Func([IDL.Nat, ItemType, IDL.Nat], [IDL.Nat], []),
  'mintLand' : IDL.Func([], [LandData], []),
  'openCache' : IDL.Func([IDL.Nat], [CacheOpenResult], []),
  'processCache' : IDL.Func([IDL.Nat], [ModifierInstance], []),
  'removeModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setGovernanceCanister' : IDL.Func([IDL.Principal], [], []),
  'setMarketplaceCanister' : IDL.Func([IDL.Principal], [], []),
  'setTokenCanister' : IDL.Func([IDL.Principal], [], []),
  'transferLand' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
  'transferModifier' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'upgradePlot' : IDL.Func([IDL.Nat, IDL.Nat], [UpgradeResult], []),
  'useBooster' : IDL.Func([BoosterKind], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'lon' : IDL.Float64 });
  const ModifierInstance = IDL.Record({
    'modifierInstanceId' : IDL.Nat,
    'modifierType' : IDL.Text,
    'model_url' : IDL.Text,
    'rarity_tier' : IDL.Nat,
    'multiplier_value' : IDL.Float64,
  });
  const LandData = IDL.Record({
    'decorationURL' : IDL.Opt(IDL.Text),
    'baseTokenMultiplier' : IDL.Float64,
    'lastChargeUpdate' : Time,
    'upgradeLevel' : IDL.Nat,
    'principal' : IDL.Principal,
    'landId' : IDL.Nat,
    'lastClaimTime' : Time,
    'biome' : IDL.Text,
    'chargeCap' : IDL.Nat,
    'cycleCharge' : IDL.Int,
    'plotName' : IDL.Text,
    'coordinates' : Coordinates,
    'attachedModifications' : IDL.Vec(ModifierInstance),
  });
  const Modifier = IDL.Record({
    'name' : IDL.Text,
    'asset_url' : IDL.Text,
    'mod_id' : IDL.Nat,
    'rarity_tier' : IDL.Nat,
    'multiplier_value' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClaimResult = IDL.Variant({
    'success' : IDL.Record({
      'tokensClaimed' : IDL.Nat,
      'newBalance' : IDL.Nat,
      'nextClaimTime' : Time,
    }),
    'mintFailed' : IDL.Text,
    'cooldown' : IDL.Record({
      'currentBalance' : IDL.Nat,
      'remainingTime' : IDL.Int,
    }),
    'insufficientCharge' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Int,
    }),
  });
  const LootCache = IDL.Record({
    'owner' : IDL.Principal,
    'tier' : IDL.Nat,
    'cache_id' : IDL.Nat,
    'discovered_at' : Time,
    'is_opened' : IDL.Bool,
  });
  const DiscoverCacheResult = IDL.Variant({
    'success' : LootCache,
    'insufficientTokens' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Nat,
    }),
    'paymentFailed' : IDL.Text,
    'insufficientCharge' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Int,
    }),
  });
  const GProposal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'votesYes' : IDL.Nat,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'votesNo' : IDL.Nat,
    'category' : IDL.Text,
    'proposer' : IDL.Principal,
  });
  const GStakerLeaderboardEntry = IDL.Record({
    'topBiome' : IDL.Text,
    'weight' : IDL.Nat,
    'principal' : IDL.Principal,
    'unclaimedRewards' : IDL.Nat,
    'stake' : IDL.Nat,
    'maxMods' : IDL.Nat,
  });
  const GStakeInfo = IDL.Record({
    'weight' : IDL.Nat,
    'lockEndsAt' : Time,
    'claimableVest' : IDL.Nat,
    'unclaimedRewards' : IDL.Nat,
    'stake' : IDL.Nat,
    'pendingVest' : IDL.Nat,
  });
  const GVoteRecord = IDL.Record({
    'weight' : IDL.Nat,
    'choice' : IDL.Bool,
    'proposalId' : IDL.Nat,
  });
  const GStakeResult = IDL.Variant({
    'transferFailed' : IDL.Text,
    'success' : IDL.Record({ 'newStake' : IDL.Nat }),
    'insufficientTokens' : IDL.Record({
      'available' : IDL.Nat,
      'required' : IDL.Nat,
    }),
  });
  const GVoteResult = IDL.Variant({
    'proposalNotFound' : IDL.Null,
    'alreadyVoted' : IDL.Null,
    'notStaker' : IDL.Null,
    'proposalNotActive' : IDL.Null,
    'success' : IDL.Record({ 'weight' : IDL.Nat }),
  });
  const ItemType = IDL.Variant({ 'Land' : IDL.Null, 'Modifier' : IDL.Null });
  const Listing = IDL.Record({
    'itemId' : IDL.Nat,
    'listingId' : IDL.Nat,
    'seller' : IDL.Principal,
    'isActive' : IDL.Bool,
    'itemType' : ItemType,
    'biome' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PublicLandInfo = IDL.Record({
    'principal' : IDL.Principal,
    'landId' : IDL.Nat,
    'biome' : IDL.Text,
  });
  const CrystalKind = IDL.Variant({
    'Cryonix' : IDL.Null,
    'Burnite' : IDL.Null,
    'Synthex' : IDL.Null,
  });
  const CrystalTier = IDL.Variant({ 'T1' : IDL.Null, 'T2' : IDL.Null });
  const CrystalItem = IDL.Record({
    'kind' : CrystalKind,
    'tier' : CrystalTier,
    'quantity' : IDL.Nat,
  });
  const KeeperHeartItem = IDL.Record({ 'biome' : IDL.Text });
  const BoosterKind = IDL.Variant({
    'B1000' : IDL.Null,
    'B250' : IDL.Null,
    'B500' : IDL.Null,
  });
  const BoosterItem = IDL.Record({
    'kind' : BoosterKind,
    'quantity' : IDL.Nat,
  });
  const FullInventory = IDL.Record({
    'crystals' : IDL.Vec(CrystalItem),
    'keeperHearts' : IDL.Vec(KeeperHeartItem),
    'boosters' : IDL.Vec(BoosterItem),
  });
  const TopLandEntry = IDL.Record({
    'upgradeLevel' : IDL.Nat,
    'principal' : IDL.Principal,
    'landId' : IDL.Nat,
    'biome' : IDL.Text,
    'tokenBalance' : IDL.Nat,
    'plotName' : IDL.Text,
  });
  const CacheDropMod = IDL.Record({
    'modId' : IDL.Nat,
    'subtype' : IDL.Text,
    'rarityTier' : IDL.Nat,
    'instanceId' : IDL.Nat,
  });
  const CacheDropItem = IDL.Variant({
    'mod' : CacheDropMod,
    'booster' : BoosterItem,
    'crystal' : CrystalItem,
    'keeperHeart' : KeeperHeartItem,
  });
  const CacheOpenResult = IDL.Record({
    'energySpent' : IDL.Nat,
    'items' : IDL.Vec(CacheDropItem),
  });
  const UpgradeResult = IDL.Variant({
    'maxLevelReached' : IDL.Null,
    'success' : IDL.Record({
      'newLevel' : IDL.Nat,
      'remainingTokens' : IDL.Nat,
    }),
    'insufficientTokens' : IDL.Record({
      'required' : IDL.Nat,
      'current' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    'adminGetLandData' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(LandData))],
        ['query'],
      ),
    'adminSetAllModifiers' : IDL.Func([IDL.Vec(Modifier)], [], []),
    'applyModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buy_item' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'cancelListing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'claimRewards' : IDL.Func([IDL.Nat], [ClaimResult], []),
    'discoverLootCache' : IDL.Func([IDL.Nat], [DiscoverCacheResult], []),
    'gAdminCloseProposal' : IDL.Func([IDL.Nat], [], []),
    'gAdminWithdrawTreasury' : IDL.Func([IDL.Nat], [], []),
    'gCalcWeight' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'gClaimVestedRewards' : IDL.Func([], [IDL.Nat], []),
    'gCreateProposal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'gGetActiveProposals' : IDL.Func([], [IDL.Vec(GProposal)], ['query']),
    'gGetAllProposals' : IDL.Func([], [IDL.Vec(GProposal)], ['query']),
    'gGetDeveloperFund' : IDL.Func([], [IDL.Nat], ['query']),
    'gGetInsuranceReserve' : IDL.Func([], [IDL.Nat], ['query']),
    'gGetLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GStakerLeaderboardEntry)],
        ['query'],
      ),
    'gGetMyStakeInfo' : IDL.Func([], [GStakeInfo], ['query']),
    'gGetMyVotes' : IDL.Func([], [IDL.Vec(GVoteRecord)], ['query']),
    'gGetStakedBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'gGetTotalWeightedStake' : IDL.Func([], [IDL.Nat], ['query']),
    'gGetTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'gReceiveIncome' : IDL.Func([IDL.Nat], [], []),
    'gStakeTokens' : IDL.Func([IDL.Nat], [GStakeResult], []),
    'gUnstakeTokens' : IDL.Func([IDL.Nat], [], []),
    'gVote' : IDL.Func([IDL.Nat, IDL.Bool], [GVoteResult], []),
    'getActiveListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllLandsPublic' : IDL.Func([], [IDL.Vec(PublicLandInfo)], ['query']),
    'getAllModifiers' : IDL.Func([], [IDL.Vec(Modifier)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFullInventory' : IDL.Func([], [FullInventory], ['query']),
    'getLandData' : IDL.Func([], [IDL.Vec(LandData)], []),
    'getLandDataById' : IDL.Func([IDL.Nat], [IDL.Opt(LandData)], ['query']),
    'getLandDataQuery' : IDL.Func([], [IDL.Opt(IDL.Vec(LandData))], ['query']),
    'getLandOwner' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
    'getLandsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LandData)],
        ['query'],
      ),
    'getModifierById' : IDL.Func([IDL.Nat], [IDL.Opt(Modifier)], ['query']),
    'getModifiersByTier' : IDL.Func([IDL.Nat], [IDL.Vec(Modifier)], ['query']),
    'getMyLootCaches' : IDL.Func([], [IDL.Vec(LootCache)], ['query']),
    'getMyModifierInventory' : IDL.Func(
        [],
        [IDL.Vec(ModifierInstance)],
        ['query'],
      ),
    'getTopLands' : IDL.Func([IDL.Nat], [IDL.Vec(TopLandEntry)], ['query']),
    'getUserListings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'list_item' : IDL.Func([IDL.Nat, ItemType, IDL.Nat], [IDL.Nat], []),
    'mintLand' : IDL.Func([], [LandData], []),
    'openCache' : IDL.Func([IDL.Nat], [CacheOpenResult], []),
    'processCache' : IDL.Func([IDL.Nat], [ModifierInstance], []),
    'removeModifier' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setGovernanceCanister' : IDL.Func([IDL.Principal], [], []),
    'setMarketplaceCanister' : IDL.Func([IDL.Principal], [], []),
    'setTokenCanister' : IDL.Func([IDL.Principal], [], []),
    'transferLand' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
    'transferModifier' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'upgradePlot' : IDL.Func([IDL.Nat, IDL.Nat], [UpgradeResult], []),
    'useBooster' : IDL.Func([BoosterKind], [], []),
  });
};

export const init = ({ IDL }) => { return []; };