/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BoosterItem { 'kind' : BoosterKind, 'quantity' : bigint }
export type BoosterKind = { 'B1000' : null } |
  { 'B250' : null } |
  { 'B500' : null };
export type CacheDropItem = { 'mod' : CacheDropMod } |
  { 'booster' : BoosterItem } |
  { 'crystal' : CrystalItem } |
  { 'keeperHeart' : KeeperHeartItem };
export interface CacheDropMod {
  'modId' : bigint,
  'subtype' : string,
  'rarityTier' : bigint,
  'instanceId' : bigint,
}
export interface CacheOpenResult {
  'energySpent' : bigint,
  'items' : Array<CacheDropItem>,
}
export type ClaimResult = {
    'success' : {
      'tokensClaimed' : bigint,
      'newBalance' : bigint,
      'nextClaimTime' : Time,
    }
  } |
  { 'mintFailed' : string } |
  { 'cooldown' : { 'currentBalance' : bigint, 'remainingTime' : bigint } } |
  { 'insufficientCharge' : { 'required' : bigint, 'current' : bigint } };
export interface Coordinates { 'lat' : number, 'lon' : number }
export interface CrystalItem {
  'kind' : CrystalKind,
  'tier' : CrystalTier,
  'quantity' : bigint,
}
export type CrystalKind = { 'Cryonix' : null } |
  { 'Burnite' : null } |
  { 'Synthex' : null };
export type CrystalTier = { 'T1' : null } |
  { 'T2' : null };
export type DiscoverCacheResult = { 'success' : LootCache } |
  { 'insufficientTokens' : { 'required' : bigint, 'current' : bigint } } |
  { 'paymentFailed' : string } |
  { 'insufficientCharge' : { 'required' : bigint, 'current' : bigint } };
export interface FullInventory {
  'crystals' : Array<CrystalItem>,
  'keeperHearts' : Array<KeeperHeartItem>,
  'boosters' : Array<BoosterItem>,
}
export interface GProposal {
  'id' : bigint,
  'title' : string,
  'votesYes' : bigint,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'votesNo' : bigint,
  'category' : string,
  'proposer' : Principal,
}
export interface GStakeInfo {
  'weight' : bigint,
  'lockEndsAt' : Time,
  'claimableVest' : bigint,
  'unclaimedRewards' : bigint,
  'stake' : bigint,
  'pendingVest' : bigint,
}
export type GStakeResult = { 'transferFailed' : string } |
  { 'success' : { 'newStake' : bigint } } |
  { 'insufficientTokens' : { 'available' : bigint, 'required' : bigint } };
export interface GStakerLeaderboardEntry {
  'topBiome' : string,
  'weight' : bigint,
  'principal' : Principal,
  'unclaimedRewards' : bigint,
  'stake' : bigint,
  'maxMods' : bigint,
}
export interface GVoteRecord {
  'weight' : bigint,
  'choice' : boolean,
  'proposalId' : bigint,
}
export type GVoteResult = { 'proposalNotFound' : null } |
  { 'alreadyVoted' : null } |
  { 'notStaker' : null } |
  { 'proposalNotActive' : null } |
  { 'success' : { 'weight' : bigint } };
export type ItemType = { 'Land' : null } |
  { 'Modifier' : null };
export interface KeeperHeartItem { 'biome' : string }
export interface LandData {
  'decorationURL' : [] | [string],
  'baseTokenMultiplier' : number,
  'lastChargeUpdate' : Time,
  'upgradeLevel' : bigint,
  'principal' : Principal,
  'landId' : bigint,
  'lastClaimTime' : Time,
  'biome' : string,
  'chargeCap' : bigint,
  'cycleCharge' : bigint,
  'plotName' : string,
  'coordinates' : Coordinates,
  'attachedModifications' : Array<ModifierInstance>,
}
export interface Listing {
  'itemId' : bigint,
  'listingId' : bigint,
  'seller' : Principal,
  'isActive' : boolean,
  'itemType' : ItemType,
  'biome' : string,
  'price' : bigint,
}
export interface LootCache {
  'owner' : Principal,
  'tier' : bigint,
  'cache_id' : bigint,
  'discovered_at' : Time,
  'is_opened' : boolean,
}
export interface Modifier {
  'name' : string,
  'asset_url' : string,
  'mod_id' : bigint,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface ModifierInstance {
  'modifierInstanceId' : bigint,
  'modifierType' : string,
  'model_url' : string,
  'rarity_tier' : bigint,
  'multiplier_value' : number,
}
export interface PublicLandInfo {
  'principal' : Principal,
  'landId' : bigint,
  'biome' : string,
}
export type Time = bigint;
export interface TopLandEntry {
  'upgradeLevel' : bigint,
  'principal' : Principal,
  'landId' : bigint,
  'biome' : string,
  'tokenBalance' : bigint,
  'plotName' : string,
}
export type UpgradeResult = { 'maxLevelReached' : null } |
  { 'success' : { 'newLevel' : bigint, 'remainingTokens' : bigint } } |
  { 'insufficientTokens' : { 'required' : bigint, 'current' : bigint } };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'adminGetLandData' : ActorMethod<[Principal], [] | [Array<LandData>]>,
  'adminSetAllModifiers' : ActorMethod<[Array<Modifier>], undefined>,
  'applyModifier' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buy_item' : ActorMethod<[bigint], boolean>,
  'cancelListing' : ActorMethod<[bigint], boolean>,
  'claimRewards' : ActorMethod<[bigint], ClaimResult>,
  'discoverLootCache' : ActorMethod<[bigint], DiscoverCacheResult>,
  'gAdminCloseProposal' : ActorMethod<[bigint], undefined>,
  'gAdminWithdrawTreasury' : ActorMethod<[bigint], undefined>,
  'gCalcWeight' : ActorMethod<[Principal], bigint>,
  'gClaimVestedRewards' : ActorMethod<[], bigint>,
  'gCreateProposal' : ActorMethod<[string, string, string], bigint>,
  'gGetActiveProposals' : ActorMethod<[], Array<GProposal>>,
  'gGetAllProposals' : ActorMethod<[], Array<GProposal>>,
  'gGetDeveloperFund' : ActorMethod<[], bigint>,
  'gGetInsuranceReserve' : ActorMethod<[], bigint>,
  'gGetLeaderboard' : ActorMethod<[bigint], Array<GStakerLeaderboardEntry>>,
  'gGetMyStakeInfo' : ActorMethod<[], GStakeInfo>,
  'gGetMyVotes' : ActorMethod<[], Array<GVoteRecord>>,
  'gGetStakedBalance' : ActorMethod<[Principal], bigint>,
  'gGetTotalWeightedStake' : ActorMethod<[], bigint>,
  'gGetTreasuryBalance' : ActorMethod<[], bigint>,
  'gReceiveIncome' : ActorMethod<[bigint], undefined>,
  'gStakeTokens' : ActorMethod<[bigint], GStakeResult>,
  'gUnstakeTokens' : ActorMethod<[bigint], undefined>,
  'gVote' : ActorMethod<[bigint, boolean], GVoteResult>,
  'getActiveListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getAllActiveListings' : ActorMethod<[], Array<Listing>>,
  'getAllLandsPublic' : ActorMethod<[], Array<PublicLandInfo>>,
  'getAllModifiers' : ActorMethod<[], Array<Modifier>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFullInventory' : ActorMethod<[], FullInventory>,
  'getLandData' : ActorMethod<[], Array<LandData>>,
  'getLandDataById' : ActorMethod<[bigint], [] | [LandData]>,
  'getLandDataQuery' : ActorMethod<[], [] | [Array<LandData>]>,
  'getLandOwner' : ActorMethod<[bigint], [] | [Principal]>,
  'getLandsByOwner' : ActorMethod<[Principal], Array<LandData>>,
  'getModifierById' : ActorMethod<[bigint], [] | [Modifier]>,
  'getModifiersByTier' : ActorMethod<[bigint], Array<Modifier>>,
  'getMyLootCaches' : ActorMethod<[], Array<LootCache>>,
  'getMyModifierInventory' : ActorMethod<[], Array<ModifierInstance>>,
  'getTopLands' : ActorMethod<[bigint], Array<TopLandEntry>>,
  'getUserListings' : ActorMethod<[Principal], Array<Listing>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'list_item' : ActorMethod<[bigint, ItemType, bigint], bigint>,
  'mintLand' : ActorMethod<[], LandData>,
  'openCache' : ActorMethod<[bigint], CacheOpenResult>,
  'processCache' : ActorMethod<[bigint], ModifierInstance>,
  'removeModifier' : ActorMethod<[bigint, bigint], undefined>,
  'setGovernanceCanister' : ActorMethod<[Principal], undefined>,
  'setMarketplaceCanister' : ActorMethod<[Principal], undefined>,
  'setTokenCanister' : ActorMethod<[Principal], undefined>,
  'transferLand' : ActorMethod<[Principal, bigint], boolean>,
  'transferModifier' : ActorMethod<[Principal, Principal, bigint], boolean>,
  'upgradePlot' : ActorMethod<[bigint, bigint], UpgradeResult>,
  'useBooster' : ActorMethod<[BoosterKind], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];