/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface LootCache {
    owner: Principal;
    tier: bigint;
    cache_id: bigint;
    discovered_at: Time;
    is_opened: boolean;
}
export interface Coordinates {
    lat: number;
    lon: number;
}
export type ClaimResult = {
    __kind__: "success";
    success: {
        tokensClaimed: bigint;
        newBalance: bigint;
        nextClaimTime: Time;
    };
} | {
    __kind__: "mintFailed";
    mintFailed: string;
} | {
    __kind__: "cooldown";
    cooldown: {
        currentBalance: bigint;
        remainingTime: bigint;
    };
} | {
    __kind__: "insufficientCharge";
    insufficientCharge: {
        required: bigint;
        current: bigint;
    };
};
export interface LandData {
    decorationURL?: string;
    baseTokenMultiplier: number;
    lastChargeUpdate: Time;
    upgradeLevel: bigint;
    principal: Principal;
    landId: bigint;
    lastClaimTime: Time;
    biome: string;
    chargeCap: bigint;
    cycleCharge: bigint;
    plotName: string;
    coordinates: Coordinates;
    attachedModifications: Array<ModifierInstance>;
}
export type DiscoverCacheResult = {
    __kind__: "success";
    success: LootCache;
} | {
    __kind__: "insufficientTokens";
    insufficientTokens: {
        required: bigint;
        current: bigint;
    };
} | {
    __kind__: "paymentFailed";
    paymentFailed: string;
} | {
    __kind__: "insufficientCharge";
    insufficientCharge: {
        required: bigint;
        current: bigint;
    };
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TopLandEntry {
    upgradeLevel: bigint;
    principal: Principal;
    tokenBalance: bigint;
    plotName: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Modifier {
    name: string;
    asset_url: string;
    mod_id: bigint;
    rarity_tier: bigint;
    multiplier_value: number;
}
export type UpgradeResult = {
    __kind__: "maxLevelReached";
    maxLevelReached: null;
} | {
    __kind__: "success";
    success: {
        newLevel: bigint;
        remainingTokens: bigint;
    };
} | {
    __kind__: "insufficientTokens";
    insufficientTokens: {
        required: bigint;
        current: bigint;
    };
};
export interface ModifierInstance {
    modifierInstanceId: bigint;
    modifierType: string;
    model_url: string;
    rarity_tier: bigint;
    multiplier_value: number;
}
export interface UserProfile {
    name: string;
}
export interface Modification {
    model_url: string;
    mod_id: bigint;
    rarity_tier: bigint;
    multiplier_value: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    adminGetLandData(user: Principal): Promise<Array<LandData> | null>;
    adminSetAllModifiers(modifier_list: Array<Modifier>): Promise<void>;
    applyModifier(modifierInstanceId: bigint, landId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimRewards(landId: bigint): Promise<ClaimResult>;
    discoverLootCache(tier: bigint): Promise<DiscoverCacheResult>;
    getAllModifiers(): Promise<Array<Modifier>>;
    getAssetCanisterCycleBalance(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentCbrBalance(): Promise<bigint>;
    getHighestRarityModification(): Promise<Modification | null>;
    getLandCanisterCycleBalance(): Promise<string>;
    getLandData(): Promise<Array<LandData>>;
    getLandDataQuery(): Promise<Array<LandData> | null>;
    getLandOwner(landId: bigint): Promise<Principal | null>;
    getModifierById(mod_id: bigint): Promise<Modifier | null>;
    getModifiersByTier(tier: bigint): Promise<Array<Modifier>>;
    getMyLootCaches(): Promise<Array<LootCache>>;
    getMyModifications(): Promise<Array<Modification>>;
    getTopLands(limit: bigint): Promise<Array<TopLandEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    mintLand(): Promise<LandData>;
    processCache(cache_id: bigint): Promise<ModifierInstance>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setGovernanceCanister(governance: Principal): Promise<void>;
    setMarketplaceCanister(marketplace: Principal): Promise<void>;
    setTokenCanister(token: Principal): Promise<void>;
    transferLand(to: Principal, landId: bigint): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateDecoration(landId: bigint, url: string): Promise<void>;
    updatePlotName(landId: bigint, name: string): Promise<void>;
    upgradePlot(landId: bigint, cost: bigint): Promise<UpgradeResult>;
    useConsumableBuff(item_id: bigint): Promise<void>;
}
import type { ClaimResult as _ClaimResult, Coordinates as _Coordinates, DiscoverCacheResult as _DiscoverCacheResult, LandData as _LandData, LootCache as _LootCache, Modification as _Modification, Modifier as _Modifier, ModifierInstance as _ModifierInstance, Time as _Time, UpgradeResult as _UpgradeResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminGetLandData(arg0: Principal): Promise<Array<LandData> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetLandData(arg0);
                return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetLandData(arg0);
            return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async adminSetAllModifiers(arg0: Array<Modifier>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetAllModifiers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetAllModifiers(arg0);
            return result;
        }
    }
    async applyModifier(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyModifier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyModifier(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async claimRewards(arg0: bigint): Promise<ClaimResult> {
        if (this.processError) {
            try {
                const result = await this.actor.claimRewards(arg0);
                return from_candid_ClaimResult_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimRewards(arg0);
            return from_candid_ClaimResult_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async discoverLootCache(arg0: bigint): Promise<DiscoverCacheResult> {
        if (this.processError) {
            try {
                const result = await this.actor.discoverLootCache(arg0);
                return from_candid_DiscoverCacheResult_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.discoverLootCache(arg0);
            return from_candid_DiscoverCacheResult_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllModifiers(): Promise<Array<Modifier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModifiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModifiers();
            return result;
        }
    }
    async getAssetCanisterCycleBalance(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetCanisterCycleBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetCanisterCycleBalance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCurrentCbrBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentCbrBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentCbrBalance();
            return result;
        }
    }
    async getHighestRarityModification(): Promise<Modification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighestRarityModification();
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighestRarityModification();
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getLandCanisterCycleBalance(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandCanisterCycleBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandCanisterCycleBalance();
            return result;
        }
    }
    async getLandData(): Promise<Array<LandData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandData();
                return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandData();
            return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
        }
    }
    async getLandDataQuery(): Promise<Array<LandData> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandDataQuery();
                return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandDataQuery();
            return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async getLandOwner(arg0: bigint): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandOwner(arg0);
                return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandOwner(arg0);
            return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getModifierById(arg0: bigint): Promise<Modifier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModifierById(arg0);
                return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModifierById(arg0);
            return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getModifiersByTier(arg0: bigint): Promise<Array<Modifier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModifiersByTier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModifiersByTier(arg0);
            return result;
        }
    }
    async getMyLootCaches(): Promise<Array<LootCache>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLootCaches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLootCaches();
            return result;
        }
    }
    async getMyModifications(): Promise<Array<Modification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyModifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyModifications();
            return result;
        }
    }
    async getTopLands(arg0: bigint): Promise<Array<TopLandEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopLands(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopLands(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async mintLand(): Promise<LandData> {
        if (this.processError) {
            try {
                const result = await this.actor.mintLand();
                return from_candid_LandData_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintLand();
            return from_candid_LandData_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async processCache(arg0: bigint): Promise<ModifierInstance> {
        if (this.processError) {
            try {
                const result = await this.actor.processCache(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processCache(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setGovernanceCanister(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGovernanceCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGovernanceCanister(arg0);
            return result;
        }
    }
    async setMarketplaceCanister(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMarketplaceCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMarketplaceCanister(arg0);
            return result;
        }
    }
    async setTokenCanister(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTokenCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTokenCanister(arg0);
            return result;
        }
    }
    async transferLand(arg0: Principal, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.transferLand(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferLand(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDecoration(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDecoration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDecoration(arg0, arg1);
            return result;
        }
    }
    async updatePlotName(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlotName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlotName(arg0, arg1);
            return result;
        }
    }
    async upgradePlot(arg0: bigint, arg1: bigint): Promise<UpgradeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradePlot(arg0, arg1);
                return from_candid_UpgradeResult_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradePlot(arg0, arg1);
            return from_candid_UpgradeResult_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async useConsumableBuff(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.useConsumableBuff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useConsumableBuff(arg0);
            return result;
        }
    }
}
function from_candid_ClaimResult_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimResult): ClaimResult {
    return from_candid_variant_n9(uploadFile, downloadFile, value);
}
function from_candid_DiscoverCacheResult_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscoverCacheResult): DiscoverCacheResult {
    return from_candid_variant_n11(uploadFile, downloadFile, value);
}
function from_candid_LandData_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandData): LandData {
    return from_candid_record_n4(uploadFile, downloadFile, value);
}
function from_candid_UpgradeResult_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpgradeResult): UpgradeResult {
    return from_candid_variant_n19(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(uploadFile, downloadFile, value);
}
function from_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_LandData>]): Array<LandData> | null {
    return value.length === 0 ? null : from_candid_vec_n2(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Modification]): Modification | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Modifier]): Modifier | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    decorationURL: [] | [string];
    baseTokenMultiplier: number;
    lastChargeUpdate: _Time;
    upgradeLevel: bigint;
    principal: Principal;
    landId: bigint;
    lastClaimTime: _Time;
    biome: string;
    chargeCap: bigint;
    cycleCharge: bigint;
    plotName: string;
    coordinates: _Coordinates;
    attachedModifications: Array<_ModifierInstance>;
}): {
    decorationURL?: string;
    baseTokenMultiplier: number;
    lastChargeUpdate: Time;
    upgradeLevel: bigint;
    principal: Principal;
    landId: bigint;
    lastClaimTime: Time;
    biome: string;
    chargeCap: bigint;
    cycleCharge: bigint;
    plotName: string;
    coordinates: Coordinates;
    attachedModifications: Array<ModifierInstance>;
} {
    return {
        decorationURL: record_opt_to_undefined(from_candid_opt_n5(uploadFile, downloadFile, value.decorationURL)),
        baseTokenMultiplier: value.baseTokenMultiplier,
        lastChargeUpdate: value.lastChargeUpdate,
        upgradeLevel: value.upgradeLevel,
        principal: value.principal,
        landId: value.landId,
        lastClaimTime: value.lastClaimTime,
        biome: value.biome,
        chargeCap: value.chargeCap,
        cycleCharge: value.cycleCharge,
        plotName: value.plotName,
        coordinates: value.coordinates,
        attachedModifications: value.attachedModifications
    };
}
function from_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: _LootCache;
} | {
    insufficientTokens: {
        required: bigint;
        current: bigint;
    };
} | {
    paymentFailed: string;
} | {
    insufficientCharge: {
        required: bigint;
        current: bigint;
    };
}): {
    __kind__: "success";
    success: LootCache;
} | {
    __kind__: "insufficientTokens";
    insufficientTokens: {
        required: bigint;
        current: bigint;
    };
} | {
    __kind__: "paymentFailed";
    paymentFailed: string;
} | {
    __kind__: "insufficientCharge";
    insufficientCharge: {
        required: bigint;
        current: bigint;
    };
} {
    return "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "insufficientTokens" in value ? {
        __kind__: "insufficientTokens",
        insufficientTokens: value.insufficientTokens
    } : "paymentFailed" in value ? {
        __kind__: "paymentFailed",
        paymentFailed: value.paymentFailed
    } : "insufficientCharge" in value ? {
        __kind__: "insufficientCharge",
        insufficientCharge: value.insufficientCharge
    } : value;
}
function from_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxLevelReached: null;
} | {
    success: {
        newLevel: bigint;
        remainingTokens: bigint;
    };
} | {
    insufficientTokens: {
        required: bigint;
        current: bigint;
    };
}): {
    __kind__: "maxLevelReached";
    maxLevelReached: null;
} | {
    __kind__: "success";
    success: {
        newLevel: bigint;
        remainingTokens: bigint;
    };
} | {
    __kind__: "insufficientTokens";
    insufficientTokens: {
        required: bigint;
        current: bigint;
    };
} {
    return "maxLevelReached" in value ? {
        __kind__: "maxLevelReached",
        maxLevelReached: value.maxLevelReached
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "insufficientTokens" in value ? {
        __kind__: "insufficientTokens",
        insufficientTokens: value.insufficientTokens
    } : value;
}
function from_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: {
        tokensClaimed: bigint;
        newBalance: bigint;
        nextClaimTime: _Time;
    };
} | {
    mintFailed: string;
} | {
    cooldown: {
        currentBalance: bigint;
        remainingTime: bigint;
    };
} | {
    insufficientCharge: {
        required: bigint;
        current: bigint;
    };
}): {
    __kind__: "success";
    success: {
        tokensClaimed: bigint;
        newBalance: bigint;
        nextClaimTime: Time;
    };
} | {
    __kind__: "mintFailed";
    mintFailed: string;
} | {
    __kind__: "cooldown";
    cooldown: {
        currentBalance: bigint;
        remainingTime: bigint;
    };
} | {
    __kind__: "insufficientCharge";
    insufficientCharge: {
        required: bigint;
        current: bigint;
    };
} {
    return "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "mintFailed" in value ? {
        __kind__: "mintFailed",
        mintFailed: value.mintFailed
    } : "cooldown" in value ? {
        __kind__: "cooldown",
        cooldown: value.cooldown
    } : "insufficientCharge" in value ? {
        __kind__: "insufficientCharge",
        insufficientCharge: value.insufficientCharge
    } : value;
}
function from_candid_vec_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LandData>): Array<LandData> {
    return value.map((x)=>from_candid_LandData_n3(uploadFile, downloadFile, x));
}
function to_candid_UserRole_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(uploadFile, downloadFile, value);
}
function to_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
